import { useNavigate } from 'react-router-dom';
import { CheckCircle2, Clock, Radio } from 'lucide-react';
import type { Market, MatchResult, TeamBrief } from '@polyrader/core/browser';
import { parsePolymarketMatch } from '../utils/match-parser';
import { OddsButton } from './OddsButton';
import type { OddsFormat } from '../utils/bet-math';
import { Badge } from '@/components/ui';
import { usePracticeSlipStore } from '../stores/practice-slip-store';
import { cn } from '../utils/cn';
import { useI18n } from '../hooks/use-i18n';
import { MarketLiquidityWarning } from './MarketLiquidityWarning';

interface MatchOddsRowProps {
  market: Market;
  className?: string;
  displayFormat?: OddsFormat;
}

function formatScheduledAt(iso: string | undefined): string {
  if (!iso) return 'TBD';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return 'TBD';
  return d.toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function isLive(market: Market): boolean {
  return market.match?.status === 'live';
}

export function MatchOddsRow({ market, className, displayFormat = 'decimal' }: MatchOddsRowProps) {
  const navigate = useNavigate();
  const { t } = useI18n();
  const addLeg = usePracticeSlipStore((s) => s.addLeg);

  const parsed = parsePolymarketMatch(market.question);
  if (!parsed) return null;

  const teamAName = market.match?.teamA.name || parsed.teamAName;
  const teamBName = market.match?.teamB.name || parsed.teamBName;
  const format = market.match?.format || parsed.format;
  const eventName = market.match?.eventName || parsed.eventName;
  const { eventStage, isMapMarket, mapNumber } = parsed;
  const [priceA, priceB] = market.outcomePrices.map((p) => parseFloat(p));
  const oddsA = priceA > 0 ? 1 / priceA : 0;
  const oddsB = priceB > 0 ? 1 / priceB : 0;
  const live = isLive(market);
  const scheduledAt = market.match?.scheduledAt ?? market.endDate;

  const matchLabel = `${teamAName} vs ${teamBName}`;
  const marketLabel = isMapMarket && mapNumber
    ? t('lobby.mapWinner', { map: mapNumber })
    : t('lobby.matchWinner');
  const teamAData = market.match?.teamDetails?.teamA;
  const teamBData = market.match?.teamDetails?.teamB;
  const lineupReady = Boolean(
    market.match?.lineups?.teamA.players.length === 5
    && market.match?.lineups?.teamB.players.length === 5,
  );

  const handleAddLeg = (side: 'a' | 'b') => {
    const selection = side === 'a' ? teamAName : teamBName;
    const odds = side === 'a' ? oddsA : oddsB;
    if (!odds || odds < 1.01) return;
    addLeg({
      id: '', // generated by store
      matchId: market.match?.matchId ?? market.conditionId,
      marketId: market.conditionId,
      selection,
      odds,
      source: 'polymarket',
      matchLabel,
      marketLabel,
      matchFormat: market.match?.format ?? parsed?.format,
    });
  };

  return (
    <div
      className={cn(
        'group flex cursor-pointer flex-col rounded-lg border border-border bg-background transition-colors hover:border-primary/35 hover:bg-accent/20',
        className,
      )}
      data-testid="match-odds-row"
      onClick={() => navigate(`/match/${market.slug}`)}
    >
      {/* Header: event + stage + status */}
      <div className="flex min-h-9 items-center justify-between border-b border-border bg-muted/15 px-3 text-xs text-muted-foreground">
        <div className="flex items-center gap-2 min-w-0">
          <span className="truncate font-medium text-foreground">{eventName}</span>
          {isMapMarket && mapNumber != null && (
            <Badge variant="secondary" className="text-[10px]">
              {t('lobby.mapWinner', { map: mapNumber })}
            </Badge>
          )}
          {eventStage && !isMapMarket && (
            <Badge variant="secondary" className="text-[10px]">
              {eventStage}
            </Badge>
          )}
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <MarketLiquidityWarning liquidity={market.liquidity} tags={market.tags} compact />
          {format && (
            <Badge variant="outline" className="rounded text-[10px]">
              {format}
            </Badge>
          )}
          {lineupReady && (
            <span className="hidden items-center gap-1 text-green sm:flex">
              <CheckCircle2 className="h-3 w-3" />
              {t('lobby.rosterReady')}
            </span>
          )}
          {live ? (
            <span className="flex items-center gap-1 text-red">
              <Radio className="h-3 w-3 animate-pulse" />
              {t('lobby.live')}
            </span>
          ) : (
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatScheduledAt(scheduledAt)}
            </span>
          )}
        </div>
      </div>

      {/* Body: teams + odds */}
      <div className="grid grid-cols-[minmax(0,1fr)_112px] items-center gap-x-3 gap-y-2 p-3">
        <LobbyTeamRow
          team={market.match?.teamA}
          fallbackName={teamAName}
          form={teamAData?.recentForm.last10Matches}
        />
        <div className="justify-self-end" onClick={(e) => e.stopPropagation()}>
            <OddsButton
              odds={oddsA}
              selection={teamAName}
              displayFormat={displayFormat}
              onClick={() => handleAddLeg('a')}
              aria-label={t('lobby.addSelection', { selection: teamAName })}
            />
        </div>
        <LobbyTeamRow
          team={market.match?.teamB}
          fallbackName={teamBName}
          form={teamBData?.recentForm.last10Matches}
        />
        <div className="justify-self-end" onClick={(e) => e.stopPropagation()}>
            <OddsButton
              odds={oddsB}
              selection={teamBName}
              displayFormat={displayFormat}
              onClick={() => handleAddLeg('b')}
              aria-label={t('lobby.addSelection', { selection: teamBName })}
            />
        </div>
      </div>
    </div>
  );
}

function LobbyTeamRow({ team, fallbackName, form = [] }: { team?: TeamBrief; fallbackName: string; form?: MatchResult[] }) {
  const name = team?.name || fallbackName;
  const rank = team?.rank && team.rank > 0 && team.rank < 999 ? `#${team.rank}` : '-';
  return (
    <div className="flex min-w-0 items-center gap-2.5">
      {team?.logo ? (
        <img src={team.logo} alt="" className="h-8 w-8 shrink-0 rounded border border-border bg-white p-1 object-contain" />
      ) : (
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded border border-border bg-muted/30 text-[10px] font-semibold text-muted-foreground">
          {initials(name)}
        </div>
      )}
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="truncate text-sm font-medium">{name}</span>
          <span className="shrink-0 font-mono text-[10px] text-muted-foreground">{rank}</span>
        </div>
        <div className="mt-1 flex h-3 items-center gap-1">
          {form.slice(0, 5).map((result, index) => (
            <span
              key={`${result.date}-${index}`}
              className={cn(
                'h-1.5 w-3 rounded-sm',
                result.result === 'win' ? 'bg-green' : result.result === 'loss' ? 'bg-red' : 'bg-muted-foreground/40',
              )}
              title={`${result.opponent} ${result.score}`}
            />
          ))}
          {form.length === 0 && <span className="text-[9px] text-muted-foreground">HLTV</span>}
        </div>
      </div>
    </div>
  );
}

function initials(name: string): string {
  return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || '?';
}
